### PR TITLE
Added PHP7.2+ version

### PR DESCRIPTION
**Pull request by Pen-y-Fan**
Based on the the Java version.
Same PHP tooling as Theatrical Players Refactoring Kata
`with tests` branch to follow.

### CODE REVIEW

**Comment by emilybache** [comment]
Someone else seems to have sent in a php version like the day before you! Please review what they've done and submit a pull request if you think they have missed anything.

**Comment by Pen-y-Fan** [comment]
Yes, I noticed, after I submitted my request 😒

Both of us must be fans of your Katas and PHP 😊. I'll see if I can make contact and pool resources 👌.

I've taken a quick look, the first differences, the build of PHP is locked at 7.4 (released Nov '19), where mine is 7.2+ (Nov '17 to now). I'll take a more detailed look, probably over the weekend 👍.

**Comment by emilybache** [comment]
Thanks!

**Comment by Pen-y-Fan** [comment]
New pull request based on the other PHP version #25 

This pull request can be closed.

**Pull request closed without merging**
