### PR TITLE
With tests

### PR DESCRIPTION
**Pull request by NicoSimoski**
Added unit tests for common lisp with reasonable coverage

### CODE REVIEW

**Comment by codecop** [comment]
Nice. This looks good. Please double check with the "approved" files e.g. in Java version
https://github.com/emilybache/SupermarketReceipt-Refactoring-Kata/tree/with_tests/java/src/test/java/dojo/supermarket
and
https://github.com/emilybache/SupermarketReceipt-Refactoring-Kata/tree/with_tests/java/src/test/java/dojo/supermarket/model
if you have all scenarios covered. if possible using the same names for tests or similar. This would help us in the future to keep all languages in sync as much as possible.

**Comment by NicoSimoski** [comment]
I checked C++ and Python with Pytest since I am most familiar with those languages and tried to find similar but more expressive names for the testcases. Are the poorly named tests part of the refactoring exercise?
I just recognized that I missed some tests. I will add them. But I am not sure if I understand the tests with loosing weight. Is there a clarification?
I skimmed over the implementation in Java and there seem to be about two times the amount of tests than in C++ or Python. Is the implementation in Java the reference?

**Comment by codecop** [comment]
Not sure about a canonical version. Often it is java or python or c++. Please see what you can do and what makes sense for you. Ideally a super set of tests of c++/python and subset of java...

**Comment by NicoSimoski** [comment]
I added the missing tests from c++ and added the tests for ReceiptPrinter from java as unit tests.

**Comment by codecop** [comment]
Thank you for following up. @emilybache vote to merge

**Comment by NicoSimoski** [comment]
Thanks for your input! :-)

**Comment by emilybache** [comment]
Thankyou!

**Pull request merged**
